import type { Metadata } from "next";
import { Geist, Geist_Mono, Cal_Sans } from "next/font/google";
import { Sans } from "./fonts";
import "./globals.css";
import QueryProvider from "./components/QueryProvider";
import Navbar from "./components/Navbar";
import SplashProvider from "./components/splash-provider";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const calSans = Cal_Sans({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-cal-sans",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${calSans.variable} ${Sans.variable} antialiased`}
      >
        <SplashProvider>
          <QueryProvider>
            <Navbar />
            <div className="mt-[60px]">{children}</div>{" "}
          </QueryProvider>
        </SplashProvider>
      </body>
    </html>
  );
}
