"use client";
import { ChangeEvent, FormEvent, useMemo, useState } from "react";
import { Check, ChevronLeft, ChevronRight, ImagePlus } from "lucide-react";
import Link from "next/link";
import { AnimatePresence, motion } from "framer-motion";
import { shirtVariants } from "@/app/data/marketplace";
const steps=["Account","Profile","Artwork","Garment","Review"];
export function ArtistSignupForm(){
 const [step,setStep]=useState(0),[done,setDone]=useState(false),[preview,setPreview]=useState(""); const active=shirtVariants.filter(v=>v.active&&v.inventory>0); const [data,setData]=useState({fullName:"",email:"",password:"",confirm:"",stageName:"",bio:"",location:"",portfolio:"",instagram:"",twitter:"",website:"",artTitle:"",artDescription:"",style:"Graphic",variant:active[0]?.id||"",color:active[0]?.availableColors[0]?.name||"",placement:"front"});
 const variant=active.find(v=>v.id===data.variant)||active[0]; const color=variant?.availableColors.find(c=>c.name===data.color)||variant?.availableColors[0];
 const input=(e:ChangeEvent<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>)=>setData({...data,[e.target.name]:e.target.value}); const next=(e:FormEvent)=>{e.preventDefault();if(step<4)setStep(step+1);else setDone(true)};
 const visual=useMemo(()=>({background:color?.hex||"#171717"}),[color]);
 if(done)return <motion.div className="signup-success" initial={{scale:.96,opacity:0}} animate={{scale:1,opacity:1}}><span><Check/></span><p className="eyebrow">Application received</p><h2>YOU’RE IN<br/>THE QUEUE.</h2><p>Thanks, {data.stageName||data.fullName}. We’ll review your work and respond within 7–10 days.</p><Link className="button button-dark" href="/">Back to One of One</Link></motion.div>;
 return <div className="signup-flow"><div className="stepper">{steps.map((s,i)=><button key={s} className={i===step?"active":i<step?"complete":""} onClick={()=>i<step&&setStep(i)}><span>{i<step?<Check/>:i+1}</span>{s}</button>)}</div><form onSubmit={next}><AnimatePresence mode="wait"><motion.div className="form-step" key={step} initial={{x:30,opacity:0}} animate={{x:0,opacity:1}} exit={{x:-30,opacity:0}}>
 {step===0&&<><FormTitle n="01" title="CREATE YOUR ACCOUNT" copy="First, the practical bit."/><div className="field-grid"><Field label="Full name" name="fullName" value={data.fullName} onChange={input} required/><Field label="Email" name="email" type="email" value={data.email} onChange={input} required/><Field label="Password" name="password" type="password" value={data.password} onChange={input} required/><Field label="Confirm password" name="confirm" type="password" value={data.confirm} onChange={input} required/></div></>}
 {step===1&&<><FormTitle n="02" title="TELL US WHO YOU ARE" copy="The person and practice behind the work."/><div className="field-grid"><Field label="Artist / stage name" name="stageName" value={data.stageName} onChange={input} required/><Field label="Location" name="location" value={data.location} onChange={input}/><label className="field full">Short biography<textarea name="bio" value={data.bio} onChange={input} rows={4} required/></label><Field label="Portfolio URL" name="portfolio" value={data.portfolio} onChange={input}/><Field label="Instagram" name="instagram" value={data.instagram} onChange={input}/><Field label="X / Twitter" name="twitter" value={data.twitter} onChange={input}/><Field label="Website" name="website" value={data.website} onChange={input}/></div></>}
 {step===2&&<><FormTitle n="03" title="SHOW US THE WORK" copy="Upload one piece that represents your practice."/><label className="upload-zone">{preview?<img src={preview} alt="Artwork preview"/>:<><ImagePlus/><b>Drop artwork here</b><span>JPG, PNG, WEBP · max 10MB</span></>}<input type="file" accept="image/*" onChange={e=>{const f=e.target.files?.[0];if(f)setPreview(URL.createObjectURL(f))}}/></label><div className="field-grid"><Field label="Artwork title" name="artTitle" value={data.artTitle} onChange={input} required/><label className="field">Style<select name="style" value={data.style} onChange={input}><option>Graphic</option><option>Abstract</option><option>Photography</option><option>Illustration</option><option>Typography</option></select></label><label className="field full">Artwork description<textarea name="artDescription" value={data.artDescription} onChange={input} rows={3}/></label></div></>}
 {step===3&&<><FormTitle n="04" title="BUILD THE EDITION" copy="Only garments currently available for production appear here."/><div className="config-layout"><div><label className="field">Garment<select name="variant" value={data.variant} onChange={e=>{const v=active.find(x=>x.id===e.target.value)!;setData({...data,variant:v.id,color:v.availableColors[0].name})}}>{active.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select></label><div className="field"><b>Garment color</b><div className="color-select">{variant?.availableColors.map(c=><button type="button" key={c.name} aria-label={c.name} className={data.color===c.name?"active":""} style={{background:c.hex}} onClick={()=>setData({...data,color:c.name})}/>)}</div><small>{data.color}</small></div><label className="field">Artwork placement<select name="placement" value={data.placement} onChange={input}><option value="front">Front</option><option value="back">Back</option><option value="front-back">Front & Back</option></select></label></div><ShirtPreview style={visual} placement={data.placement} image={preview}/></div></>}
 {step===4&&<><FormTitle n="05" title="ONE LAST LOOK" copy="Review your application before it enters curation."/><div className="review-grid"><div><span>Artist</span><h3>{data.stageName||data.fullName}</h3><p>{data.bio||"No biography added."}</p><small>{data.location}</small></div><div><span>Artwork</span>{preview?<img src={preview} alt="Artwork"/>:<p>No preview uploaded</p>}<h3>{data.artTitle}</h3><small>{data.style}</small></div><div><span>Edition</span><ShirtPreview style={visual} placement={data.placement} image={preview}/><h3>{variant?.name}</h3><small>{data.color} · {data.placement}</small></div></div></>}
 </motion.div></AnimatePresence><div className="form-nav">{step>0?<button type="button" onClick={()=>setStep(step-1)}><ChevronLeft/> Back</button>:<span/>}<button className="button button-dark" type="submit">{step===4?"Submit application":"Continue"}<ChevronRight/></button></div></form></div>;
}
function FormTitle({n,title,copy}:{n:string;title:string;copy:string}){return <div className="form-title"><span>{n} / 05</span><h2>{title}</h2><p>{copy}</p></div>}
function Field(props:React.InputHTMLAttributes<HTMLInputElement>&{label:string}){const {label,...rest}=props;return <label className="field">{label}<input {...rest}/></label>}
function ShirtPreview({style,placement,image}:{style:{background:string};placement:string;image:string}){return <div className="shirt-preview"><div className="shirt-shape" style={style}><i/><i/>{image&&<img src={image} alt="" className={placement==="back"?"art back":"art"}/>}<b>{placement==="front-back"?"FRONT + BACK":placement.toUpperCase()}</b></div></div>}
